comment: false

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 95%
        informational: true
    patch:
      default:
        target: auto
        threshold: 95%
        informational: true
