comment: false

coverage:
  status:
    project:
      default:
        target: 100%%
        threshold: 1%
        informational: false
    patch:
      default:
        target: 100%
        threshold: 1%
        informational: false
